version: '3'

services:

  backend-dev:
    build:
      context: .
    volumes:
      - ./:/home/www/app

  backend-slim:
    build:
      context: .
      args:
        - DJANGO_ENV=development
      dockerfile: ./Dockerfile-slim

  backend-prod:
    build:
      context: .
      args:
        - DJANGO_ENV=production
    ports:
      - "80:8000"
    command: ["gunicorn", "--bind", "0:8000", "config.wsgi"]