version: '3'

services:

  #############################################################################
  # Development services
  #############################################################################

  # Database
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pwd
    ports:
      - "5432:5432"

  # Cache backend & Celery backend
  redis:
    image: redis:5
    ports:
      - "6379:6379"

  # Backend service
  backend-dev: &backend-dev
    build:
      dockerfile: ci/Dockerfile
      context: .
      args:
        - DJANGO_ENV=development
    volumes:
      - ./:/home/www/app
    ports:
      - "8000:8000"
    command: python manage.py runserver_plus 0.0.0.0:8000
    depends_on:
      - postgres
      - redis

  # Celery worker
  celery-worker-dev:
    <<: *backend-dev
    ports:
      []
    command: celery -A config.celery:app worker --loglevel=INFO
    depends_on:
      - backend-dev

  #############################################################################
  # Production services
  #############################################################################

  # Backend service
  backend: &backend
    build:
      dockerfile: ci/Dockerfile
      context: .
      args:
        - DJANGO_ENV=production
    volumes:
      - ./:/home/www/app
    env_file:
      - .env

  # Celery worker
  celery-worker:
    <<: *backend
    ports:
      []
    command: celery -A config.celery:app worker --loglevel=INFO

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./ci/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/html/static/
    depends_on:
      - backend
