version: '3'

services:

  backend-dev:
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        - DJANGO_ENV=development
    volumes:
      - ./db:/home/www/app/db
      - ./:/home/www/app/
    ports:
      - "8000:8000"
    networks:
      - network-dev
      - default
    depends_on:
       - db-dev
    links:
       - db-dev:db-dev
    healthcheck:
      test: curl --fail -s http://localhost:8000/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

  db-dev:
    image: postgres:12
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_pwd
    ports:
      - "5432:5432"
    networks:
      - network-dev

  backend-prod:
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        - DJANGO_ENV=production
    volumes:
      - .:/home/www/app
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000
    networks:
      - network-prod
      - default
    depends_on:
       - db-prod
    links:
       - db-prod:db-prod

  db-prod:
    image: postgres:12
    environment:
      - POSTGRES_DB=prod_db
      - POSTGRES_USER=prod_user
      - POSTGRES_PASSWORD=prod_pwd
    ports:
      - "5432:5432"
    networks:
      - network-prod

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/html/static/
    depends_on:
      - backend-prod

  redis:
    image: 'bitnami/redis:6.0.16'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - network-prod
      - default
    ports:
      - "6379:6379"

  worker-dev:
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        - DJANGO_ENV=development
    volumes:
      - ./db:/home/www/app/db
      - ./:/home/www/app/
    ports:
      [ ]
    command: celery -A config.celery:app worker --loglevel=INFO
    depends_on:
      - backend-dev

  worker-prod:
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        - DJANGO_ENV=production
    volumes:
      - ./db:/home/www/app/db
      - ./:/home/www/app/
    ports:
      [ ]
    command: celery -A config.celery:app worker --loglevel=INFO
    depends_on:
      - backend-prod

networks:
  default:
  network-dev:
  network-prod:
