# Generated by Django 3.1.2 on 2020-10-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spaceship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('ship_class', models.CharField(choices=[('W', 'Warrior'), ('P', 'Pirate'), ('M', 'Merchant'), ('D', 'Diplomat')], default='W', max_length=1, verbose_name='Spaceship class')),
                ('speed', models.IntegerField(default=100, help_text='Spaceship speed', verbose_name='Speed')),
                ('hp', models.IntegerField(default=0, help_text='Spaceship Hit Points', verbose_name='Hit Points')),
                ('max_distance', models.IntegerField(default=0, help_text='Spaceship Max Distance for Hyper-jump', verbose_name='Max Distance')),
            ],
        ),
    ]
