# Generated by Django 3.1.2 on 2020-10-31 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space_rangers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spaceship',
            name='pilot',
        ),
        migrations.AddField(
            model_name='pilot',
            name='spaceship',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space_rangers.spaceship'),
        ),
    ]
