# Generated by Django 3.1.2 on 2020-10-31 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space_rangers', '0002_auto_20201031_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilot',
            name='spaceship',
        ),
        migrations.AddField(
            model_name='spaceship',
            name='pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spaceships', to='space_rangers.pilot'),
        ),
    ]
