# Generated by Django 3.1.2 on 2020-10-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_rangers', '0003_default_spaceships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spaceship',
            name='description',
        ),
    ]
