# Generated by Django 3.1.2 on 2020-11-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_rangers', '0003_auto_20201031_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='fractions',
            field=models.ManyToManyField(related_name='pilots', related_query_name='all_spaceships', through='space_rangers.PilotFraction', to='space_rangers.Fraction'),
        ),
    ]
