# Generated by Django 3.1.2 on 2020-10-04 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_rangers', '0004_remove_spaceship_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spaceship',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelTable(
            name='spaceship',
            table='spaceships',
        ),
    ]
