# Generated by Django 3.1.2 on 2020-11-01 02:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_rangers', '0004_auto_20201101_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceship',
            name='current_hp',
            field=models.IntegerField(default=0, help_text='Spaceship Hit Points', validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Current Hit Points'),
        ),
        migrations.AlterField(
            model_name='spaceship',
            name='max_hp',
            field=models.IntegerField(default=1, help_text='Spaceship Hit Points', verbose_name='Maximum Hit Points'),
        ),
    ]
