# Generated by Django 3.1.2 on 2020-11-01 05:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('space_rangers', '0005_auto_20201101_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spaceship',
            name='current_hp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Current Hit Points'),
        ),
        migrations.AlterField(
            model_name='spaceship',
            name='max_hp',
            field=models.IntegerField(default=1, verbose_name='Maximum Hit Points'),
        ),
    ]
