# Generated by Django 3.1.2 on 2020-10-04 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_rangers', '0005_auto_20201004_0746'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spaceship',
            unique_together={('name', 'ship_class')},
        ),
    ]
