# Generated by Django 3.1.2 on 2021-02-20 04:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_rangers', '0006_auto_20201101_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceship',
            name='max_hp',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(limit_value=1000)], verbose_name='Maximum Hit Points'),
        ),
    ]
