# Generated by Django 3.1.2 on 2021-02-20 04:12

from django.db import migrations, models
import space_rangers.models


class Migration(migrations.Migration):

    dependencies = [
        ('space_rangers', '0007_auto_20210220_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceship',
            name='speed',
            field=models.IntegerField(default=100, help_text='Spaceship speed', validators=[space_rangers.models.validate_speed], verbose_name='Speed'),
        ),
    ]
