# Generated by Django 3.1.2 on 2020-10-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_rangers', '0008_auto_20201004_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
        ),
    ]
