# Generated by Django 3.1.2 on 2020-10-04 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space_rangers', '0009_fraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotFraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_rangers.fraction')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_rangers.pilot')),
            ],
        ),
    ]
